### ISSUE TITLE
페이지 로드 시, fade-in 효과주기

### ISSUE THREAD

**Issue by devSoyoung** [devSoyoung/WEB-FE-study#19]
opacity를 애니메이션으로 n초동안 0에서 1까지 주면 됨

```css
div {
	animation: fadein 0.5s;
}

@keyframes fadein {
	from { opacity: 0; }
	to { opacity: 1; }
}
```

- - - -
## 참고링크
* [CSS 페이지로드시 fade in 효과주기](https://kutar37.tistory.com/entry/CSS-%ED%8E%98%EC%9D%B4%EC%A7%80%EB%A1%9C%EB%93%9C%EC%8B%9C-fade-in-%ED%9A%A8%EA%B3%BC%EC%A3%BC%EA%B8%B0)
