### ISSUE TITLE
[CSS] 클래스명 없는 태그 선택하기

### ISSUE THREAD

**Issue by devSoyoung** [devSoyoung/WEB-FE-study#40]
## 클래스 명이 빈 경우
`<div class="">` 인 경우

```css
div[class=""] {
    color: red;
}
```

## 클래스 애트리뷰트를 가지지 않는 경우
`<div>` 인 경우

```css
div:not([class]) {
    color: red;
}
```
