### ISSUE TITLE
:last-of-type

### ISSUE THREAD

**Issue by devSoyoung** [devSoyoung/WEB-FE-study#48]
https://developer.mozilla.org/en-US/docs/Web/CSS/:last-of-type

해당 요소의 형제 중 마지막 요소에 적용되는 셀렉터

```html
<h2>Heading</h2>
<p>Paragraph 1</p>
<p>Paragraph 2</p>
```

```css
p:last-of-type {
  color: red;
  font-style: italic;
}
```

<img src="https://user-images.githubusercontent.com/42922453/122145516-5a44c180-ce90-11eb-9f8b-8a467e91c81a.png" width="500" alt="결과">

- 클래스에는 적용되지 않음 ^^;
   _ref. https://stackoverflow.com/a/13211666_
